version: '3'
services:
  client:
    container_name: client
    build:
      context: ./client
      dockerfile: prod.Dockerfile
      args:
        NEXTAUTH_URL: ${NEXTAUTH_URL}
        NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
    restart: always
    ports:
      - 3000:3000
    networks:
      - my_network

  server:
    build:
      context: server
      dockerfile: server/Dockerfile
    ports:
      - "8085:8085"
#    volumes:
#      - .:/app
    depends_on:
      - db
    env_file:
      - server/.env

  db:
    build:
      context: server
      dockerfile: server/docker/postgresql/Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
