version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
#    volumes:
#      - .:/app
    depends_on:
      - db
    env_file:
      - .env
  db:
    build:
      context: .
      dockerfile: docker/postgresql/Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
